### ISSUE TITLE
presentSettingsFromViewController crash app

### ISSUE THREAD

**Issue by texzue** [iZettle/sdk-ios#158] opened 2017-09-05 16:29 UTC
Error when pressing back button after settings view is displayed on iPhone 6 IOS 11

'Can't call popNavigationItemAnimated directly on a UINavigationBar managed by a controller'

Error on IOS 11

**Comment by arikis** [comment] 2017-09-05 20:34
Thanks for letting us know, we’ll take a look at this.

**Comment by arikis** [comment] 2017-09-07 11:36
@texzue I'm unable to reproduce this bug with the Example app on iPhone 6 with iOS 11. Could you share stack trace from this crash?

**Comment by texzue** [comment] 2017-09-07 16:27
Sure 

**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot call popNavigationItemAnimated: directly on a UINavigationBar managed by a controller.'
First throw call stack:
(0x186eebd38 0x186400528 0x186eebc80 0x190402d4c 0x101e7c20c 0x1902b3f6c 0x1902b3eec 0x19029ecac 0x1902b37e0 0x1902b3300 0x1902ae7d0 0x19027fde8 0x190ba2ca0 0x190ba5110 0x190b9e27c 0x186e94358 0x186e942d8 0x186e93b60 0x186e91738 0x186db22d8 0x188c37f84 0x1902e35e0 0x100fc4b58 0x1868d656c)
libc++abi.dylib: terminating with uncaught exception of type NSException
![img_0493](https://user-images.githubusercontent.com/3408757/30173995-28651134-93bf-11e7-80cb-10cc3fcacd66.PNG)**

This error as I said only occurs on IOS 11, the app even shows a different button, UINavigationButton with title "Cancel" changes to "<-" as shown in picture

**Comment by arikis** [comment] 2017-09-08 07:39
@texzue, the issue has been found and is now fixed at our side. It will be a part of next SDK release during next week.

**Closed by arikis** 2017-09-08 07:39 UTC
Labels: Bug
