### ISSUE TITLE
SDK not remembering authentication

### ISSUE THREAD

**Issue by Clancey** [iZettle/sdk-ios#430] opened 2023-04-05 02:40 UTC
Multiple times a day when we go to credit card payments we are presented with a login screen. 

I would expect the auth tokens to persist and refresh automatically without the need for us to log back in.

**Comment by ppeelen** [comment] 2023-04-05 08:12
Hi @Clancey.

Thank you for raising this. This is not an issue we recognise and this should not happen for card payments. In order for us to investigate this further we would need more information from you, we would therefor like to request that you create a support ticket at https://developer.zettle.com so we can assist you further and find the root cause of your issue.

**Comment by ppeelen** [comment] 2023-04-05 13:52
Due to insufficient information and since we cannot re-create the issue, I will now close this issue. Please reach out to us again with more if your issue persists or create a support ticket as suggested above.

**Closed by ppeelen** 2023-04-05 13:52 UTC
