### ISSUE TITLE
Frozen approved screen (when battery is very low)

### ISSUE THREAD

**Issue by basvandorst** [iZettle/sdk-ios#440] opened 2023-09-28 14:39 UTC
# Expected Behavior

Callback for a failed or successful transaction

# Current Behavior

![image](https://github.com/iZettle/sdk-ios/assets/1196963/9fd407a2-b673-417d-84d3-8160d24b7c40)

# Context

We had similar issues before, but much less after the 3.5.0 release: https://github.com/iZettle/sdk-ios/releases/tag/3.5.0
Unfortunately we still have the issue in some cases (<1%). Most probably related battery percentage, because we only experience it when the battery is very low.  

* Operating Version: iOS
* SDK version: 3.13.2

## Failure Logs

N/A

**Comment by ppeelen** [comment] 2023-10-06 11:30
Hi @basvandorst!

Thank you for your report. We are currently investigating this issue but have so far not been able to reproduce it.
Could you please send us the software version of the readers you have connected? You should be able to find this using the Settings > Readers > Connected reader. It should a table with information such as the card reader model, software version and program version. If you could be so kind to share that, it might help us in our investigation.

Thank you in advance!

**Comment by basvandorst** [comment] 2023-10-19 12:39
Thanks @ppeelen, just contacted our partner who experienced these kind of problems. They will let me know when it occurs again and send me the requested information.

**Comment by ppeelen** [comment] 2023-12-19 06:42
Hi @basvandorst!

Do you have any further updates regarding this issue as we were not able to reproduce it?

**Comment by basvandorst** [comment] 2023-12-19 10:13
@ppeelen just checked the status of this issue by our partner. They haven't seen this issue in the last 2 months. Note; now they always double check the power cables after each installation, so they made sure all devices are continuously power connected. 

Consider it as closed for now, since we haven't experienced it the last months +  don't have concrete steps to reproduce the issue.

**Comment by ppeelen** [comment] 2024-01-01 13:59
Thank you Bas for your update. I will now close this issue, but please do not hesitate to reach out to us again if this, or any other issue for that matter, would occur.

Best regards,
Paul Peelen

**Closed by ppeelen** 2024-01-01 13:59 UTC
