### ISSUE TITLE
Memory leak with `NSDateFormatter`

### ISSUE THREAD

**Issue by Rahish** [iZettle/sdk-ios#210] opened 2018-09-05 05:57 UTC
Hello Team iZettle,

We are having issue related to memory size when using the iZettle SDK in the project. This is actually happening with the DateFormatter. 
I reviewed my code many times with my team and we found no issue in that. And Even Analysed and Profile the Project which was showing everything is ok. 

Even to confirm things we created a demo project, where we are Adding the DateFormatter Objects in the Array on taping a button. 
In the simple demo memory is increasing in bytes only as we are storing objects in Global Array. 
and when we add the iZettle in the same demo and just import that in the project it started increasing the MBs

Link for demo app: https://we.tl/t-QO2NcIY3ZD

Below are some screenshots where you can see the difference too.

![screen shot 2018-09-05 at 10 45 49 am](https://user-images.githubusercontent.com/10860828/45073345-93a34c80-b0fc-11e8-9d19-cb3a2eba4e98.png)
![screen shot 2018-09-05 at 10 46 42 am](https://user-images.githubusercontent.com/10860828/45073347-943be300-b0fc-11e8-9f71-fff2861b0aad.png)

**Comment by valkovsky** [comment] 2018-09-06 09:59
Hi Rahish!

The issue you see is expected behaviour of how frameworks work. When you add a pod to your project you link your project against the framework this pod represents. When application is launched linked frameworks are loaded into memory and reside in memory. This is why you see increasing memory consumption.

You can use any other pod (try pod with big enough size to easily see memory increasing) with your project and see that the behaviour is the same.

Best,
Andrei
iOS Developer @iZettle

**Comment by Rahish** [comment] 2018-09-06 11:01
Yes Andrei, your'e right. But our concern is why memory increasing continuously whenever we use DateFormatter. It'll increased by 100 or 200mb every time we call DateFormatter in our project(Also in the attached demo project. When we tap button on the screen). This is the problem which we are looking for. Hope will get any solution from you.

**Comment by valkovsky** [comment] 2018-09-06 11:29
Hi Rahish!

Oh! Then this is a memory leak. We will investigate the problem. Thank you for report!

**Comment by arikis** [comment] 2018-09-06 11:49
Hi @Rahish, we've identified the memory leak and we'll build a new SDK version containing the fix today.

**Comment by Rahish** [comment] 2018-09-06 12:07
Hey Guys @valkovsky and @arikis
Good to hear, that you guys found issues. 

Please take a look at Dateformater  extension, as we identified the issue is related to that mostly i.e whenever we were creating new instance for DateFormatter that was causing issue.

Good Luck (y)

Thanks

**Comment by Rahish** [comment] 2018-09-10 09:34
Hi @arikis,

When should we get the update?

**Comment by arikis** [comment] 2018-09-11 05:37
Hey @Rahish, we will release new update sometime today.

**Comment by Rahish** [comment] 2018-09-12 07:29
Hi @arikis,

When should we get the updated pod(v1.7.2)?

**Comment by arikis** [comment] 2018-09-17 05:17
Hey @Rahish, we have delayed the release for few days since we need to get few more bug fixes in. For now, you can checkout the prerelease build in https://github.com/iZettle/sdk-ios/pull/211.

**Comment by Rahish** [comment] 2018-09-24 10:51
Hi @arikis,

Any update guys? When can we expect the next release?
We are using pods, so we decided to use the best release version, so just mention the expected date to release so we can schedule things at our end.

**Comment by arikis** [comment] 2018-09-25 14:32
Hi @Rahish, we'll release the update mid next week.

**Comment by Rahish** [comment] 2018-10-17 05:54
Hi @arikis,

Any update on when should we get the latest release?. Its been more than 3 weeks and no news from your side.

**Comment by arikis** [comment] 2018-11-09 08:37
Hey @Rahish, the fix is now released with latest SDK release

**Closed by arikis** 2018-11-09 08:37 UTC
Labels: bug, release

**Comment by Rahish** [comment] 2018-11-12 07:01
Great
Thanks for update
