### ISSUE TITLE
iOS 11 New Device Registration

### ISSUE THREAD

**Issue by JulzPolz** [iZettle/sdk-ios#177] opened 2017-11-30 15:18 UTC
If you have a clean iOS11 on your iOS device and wish to register a new iZettle payment device, it fails.

To replicate:

- Reset an iPad and re-install any version of iOS11.
- Pair and iZettle terminal with your iOS device with bluetooth.
- Open latest iZettle app or any app which supports the MFi device on the App Store.
- Run through setup for the device.
- Although device is connected perfectly with bluetooth, no app will be able to connect with this new device and simply displays the attached error.

Right now we can:
- Connect without issue on iOS10
- Work on iOS11 with a device that has previously been connected under iOS10

We have tried everything and still nothing seems to work. The last version of iOS which seems to have been working is iOS 10.3.3, which it is now impossible to downgrade too. This all means that if you have a new merchant who would like to connect a new device and their iOS is at 11 or higher, then they simply cannot work with iZettle!

![image uploaded from ios](https://user-images.githubusercontent.com/153706/33438112-cc080116-d5e1-11e7-9d18-f2f8b5202a87.jpg)

Any help is appreciated.

Julian

**Comment by arikis** [comment] 2017-11-30 15:21
Hi @JulzPolz, we're aware of this issue with iOS 11 devices. Right now, we're talking with Apple to see how it can be resolved.

I'll post an update as soon as we have more info.

**Comment by JulzPolz** [comment] 2017-11-30 16:06
Hi Arikis, thanks for this. Is there a workaround that we can employ until we hear back from Apple? I just want to see if we can get something sorted in the short term as we might not get a super fast response from Apple.

**Comment by arikis** [comment] 2017-12-01 10:03
We've been unable to find a workaround after 11.0.3. Only thing that I can recommend right now is to downgrade the device to iOS 10. We're also advising our merchants to not update to iOS 11 until the issue is resolved.

We managed to reproduce it using steps defined above. We're sending diagnostics to Apple and I'll update as soon as we get response.

**Comment by JulzPolz** [comment] 2017-12-01 13:13
Hi Arikis, thanks for your reply. How do we downgrade a device to iOS10? I have had a look online and have found no helpful guides on how to do this.

**Comment by arikis** [comment] 2017-12-01 14:42
It looks like Apple stopped signing iOS 10, so unfortunately, it's not possible to downgrade to iOS 10. Is there a possibility of using another iOS 10 device?

**Comment by JulzPolz** [comment] 2017-12-01 16:20
iOS10 devices are very rare now. Out of all of the new merchants / stores that have arrived in the past week, I have only seen one iOS10 device. boarding. You cant even buy a device with iOS 10 on it now. I'd say that right now its 95% iOS11 for new merchant on

Is there not a quick "beta" workaround you guys can add as part of the SDK? Even if its "closed beta" for us to test with you? I'm just not confident how quickly apple will respond to this. Every day that goes by without a fix and/or workaround for this iZettle will be loosing out on new customer on boarding to other payment providers.

**Comment by arikis** [comment] 2017-12-01 17:02
We've found out that issue is fixed in iOS 11.2 Developer Beta 5 (I haven't checked public beta). However, those betas are meant to be used for development purposes. I think that the iOS 11.2 will be released to public next week or week after that. 

We've also found out that devices that had iOS 10 and were upgraded to iOS 11 are working perfectly normal. It's only devices with clean iOS 11 installations that have problems.

**Comment by JulzPolz** [comment] 2017-12-01 17:23
Thanks for finding that out. That does help for out testing at least. Good also to know that its been confirmed as an Apple issue.

**Comment by arikis** [comment] 2017-12-02 12:08
Good news, iOS 11.2 was released this morning. I’ve confirmed that it solves the problem with Bluetooth connectivity. Please try it out and let us know if it worked.

**Comment by JulzPolz** [comment] 2017-12-04 13:32
Thanks for your help on this. 11.2 seems to have done the trick.

**Closed** 2017-12-04 13:53 UTC
